import type { Board, BoardDetail, BoardSummary, Column, Task } from "../types";
import { ApiError } from "./apiError";
import * as endpoints from "./generated/endpoints";
import type { CreateBoardInput as GeneratedCreateBoardInput } from "./generated/model/createBoardInput";
import type { UpdateBoardInput as GeneratedUpdateBoardInput } from "./generated/model/updateBoardInput";
import type { CreateColumnInput as GeneratedCreateColumnInput } from "./generated/model/createColumnInput";
import type { UpdateColumnInput as GeneratedUpdateColumnInput } from "./generated/model/updateColumnInput";
import type { CreateTaskInput as GeneratedCreateTaskInput } from "./generated/model/createTaskInput";
import type { UpdateTaskInput as GeneratedUpdateTaskInput } from "./generated/model/updateTaskInput";
import type { MoveTaskInput as GeneratedMoveTaskInput } from "./generated/model/moveTaskInput";

/**
 * ============================================================================
 * Centralized backend access point.
 *
 * Every network call the frontend makes goes through this module. Each
 * function wraps the matching typed `fetch` function in ./generated/endpoints
 * (generated by orval from ../../../openapi.yaml — `npm run generate:api`,
 * see orval.config.ts) and normalizes the result:
 *
 *   - 2xx → resolves with the response body (typed from the contract);
 *   - any other status → rejects with an `ApiError` carrying the `code` and
 *     `message` from the `{ error: { code, message } }` envelope
 *     (`_docs/specs.md` §14);
 *   - no usable response (server down, DNS, CORS, a 502/503/504 or non-JSON
 *     body from a proxy) → rejects with an `ApiError` of code `NETWORK_ERROR`.
 *
 * Requests go to the relative `/api` prefix (`servers` in openapi.yaml), so
 * in production the API is served same-origin and in development Vite proxies
 * `/api` to the FastAPI server (see vite.config.ts and ../../../server/README.md).
 *
 * The request/response types are the generated ones, so a contract change in
 * openapi.yaml surfaces as a type error at every call site until handled.
 * ============================================================================
 */

interface ApiResponse {
  data: unknown;
  status: number;
}

const NETWORK_ERROR_MESSAGE = "Could not reach the server. Please try again.";
const GATEWAY_STATUSES = new Set([502, 503, 504]);

/** The `data` type of the successful (2xx) member of a generated response union. */
type SuccessData<R extends ApiResponse> = Extract<R, { status: 200 | 201 | 204 }>["data"];

function isErrorEnvelope(body: unknown): body is { error: { code: string; message: string } } {
  if (typeof body !== "object" || body === null || !("error" in body)) return false;
  const error = (body as { error: unknown }).error;
  return (
    typeof error === "object" &&
    error !== null &&
    typeof (error as { code?: unknown }).code === "string" &&
    typeof (error as { message?: unknown }).message === "string"
  );
}

/**
 * Awaits a generated endpoint call and either returns its 2xx payload or throws
 * an `ApiError`, so callers (the hooks in src/hooks) never see raw statuses.
 */
async function unwrap<R extends ApiResponse>(request: Promise<R>): Promise<SuccessData<R>> {
  let response: R;
  try {
    response = await request;
  } catch {
    // `fetch` itself rejected (server unreachable, CORS, aborted) or the body
    // wasn't JSON (e.g. an HTML error page from a proxy).
    throw new ApiError("NETWORK_ERROR", NETWORK_ERROR_MESSAGE);
  }

  if (response.status >= 200 && response.status < 300) {
    return response.data as SuccessData<R>;
  }

  if (isErrorEnvelope(response.data)) {
    throw new ApiError(response.data.error.code, response.data.error.message);
  }
  if (GATEWAY_STATUSES.has(response.status)) {
    // A proxy (Vite in dev, a reverse proxy in prod) answered because the
    // backend itself didn't — same situation as a failed fetch for the user.
    throw new ApiError("NETWORK_ERROR", NETWORK_ERROR_MESSAGE);
  }
  throw new ApiError("HTTP_ERROR", `Request failed with status ${response.status}`);
}

// ---------------------------------------------------------------------------
// Boards
// ---------------------------------------------------------------------------

export type CreateBoardInput = GeneratedCreateBoardInput;
export type UpdateBoardInput = GeneratedUpdateBoardInput;

function listBoards(): Promise<BoardSummary[]> {
  return unwrap(endpoints.listBoards());
}

function getBoard(boardId: string): Promise<BoardDetail> {
  return unwrap(endpoints.getBoard(boardId));
}

function createBoard(input: CreateBoardInput): Promise<Board> {
  return unwrap(endpoints.createBoard(input));
}

function updateBoard(boardId: string, input: UpdateBoardInput): Promise<Board> {
  return unwrap(endpoints.updateBoard(boardId, input));
}

function deleteBoard(boardId: string): Promise<void> {
  return unwrap(endpoints.deleteBoard(boardId));
}

// ---------------------------------------------------------------------------
// Columns
// ---------------------------------------------------------------------------

export type CreateColumnInput = GeneratedCreateColumnInput;
export type UpdateColumnInput = GeneratedUpdateColumnInput;

function createColumn(boardId: string, input: CreateColumnInput): Promise<Column> {
  return unwrap(endpoints.createColumn(boardId, input));
}

function updateColumn(columnId: string, input: UpdateColumnInput): Promise<Column> {
  return unwrap(endpoints.updateColumn(columnId, input));
}

function deleteColumn(columnId: string): Promise<void> {
  return unwrap(endpoints.deleteColumn(columnId));
}

function reorderColumns(boardId: string, columnIds: string[]): Promise<Column[]> {
  return unwrap(endpoints.reorderColumns(boardId, { columnIds }));
}

// ---------------------------------------------------------------------------
// Tasks
// ---------------------------------------------------------------------------

export type CreateTaskInput = GeneratedCreateTaskInput;
export type UpdateTaskInput = GeneratedUpdateTaskInput;
export type MoveTaskInput = GeneratedMoveTaskInput;

function createTask(columnId: string, input: CreateTaskInput): Promise<Task> {
  return unwrap(endpoints.createTask(columnId, input));
}

function getTask(taskId: string): Promise<Task> {
  return unwrap(endpoints.getTask(taskId));
}

function updateTask(taskId: string, input: UpdateTaskInput): Promise<Task> {
  return unwrap(endpoints.updateTask(taskId, input));
}

function deleteTask(taskId: string): Promise<void> {
  return unwrap(endpoints.deleteTask(taskId));
}

function moveTask(taskId: string, input: MoveTaskInput): Promise<Task> {
  return unwrap(endpoints.moveTask(taskId, input));
}

// ---------------------------------------------------------------------------

export const api = {
  listBoards,
  getBoard,
  createBoard,
  updateBoard,
  deleteBoard,
  createColumn,
  updateColumn,
  deleteColumn,
  reorderColumns,
  createTask,
  getTask,
  updateTask,
  deleteTask,
  moveTask,
};

export type Api = typeof api;
