/**
 * Domain types, re-exported from the OpenAPI-generated schemas
 * (src/api/generated/model, generated by orval from ../../../openapi.yaml —
 * run `npm run generate:api` after editing that file) so they can't drift
 * from the backend contract. Server-managed fields (id, position, createdAt,
 * updatedAt, ...) are `readonly` there; the frontend never mutates entities
 * in place (optimistic updates in src/utils/boardTransforms.ts build new
 * objects), so that's the correct shape for the whole app.
 */

export type {
  Board,
  BoardSummary,
  Column,
  ColumnWithTasks,
  BoardDetail,
  Task,
  Priority,
} from "../api/generated/model";
import { Priority as PriorityEnum } from "../api/generated/model/priority";
import type { Priority } from "../api/generated/model/priority";

export const PRIORITIES: Priority[] = [PriorityEnum.LOW, PriorityEnum.MEDIUM, PriorityEnum.HIGH];

/**
 * Mirrors the generated `Error` schema (src/api/generated/model/error.ts).
 * Not re-exported directly under that name because it would shadow the
 * built-in `Error` type wherever imported.
 */
export interface ApiErrorShape {
  error: {
    code: string;
    message: string;
  };
}
