/**
 * Domain types. `Priority` is re-exported from the OpenAPI-generated schema
 * (src/api/generated/model/priority.ts, generated by orval from
 * ../../../openapi.yaml — run `npm run generate:api` after editing that
 * file) so the enum can't drift from the documented contract.
 *
 * The entity types below (Board, Column, Task, ...) are intentionally
 * hand-written rather than re-exported the same way: the generated versions
 * mark server-managed fields (id, position, createdAt, updatedAt, ...)
 * `readonly`, which is correct for API request/response types but wrong for
 * these — the mock backend in src/api/client.ts *is* the server for now, and
 * needs to mutate those fields in its own storage layer. They're kept
 * structurally identical to src/api/generated/model on purpose; the
 * generated request DTOs (CreateBoardInput, UpdateTaskInput, ...), which the
 * mock only ever reads, are sourced from the generated schemas directly in
 * src/api/client.ts.
 */

export type { Priority } from "../api/generated/model/priority";
import { Priority as PriorityEnum } from "../api/generated/model/priority";
import type { Priority } from "../api/generated/model/priority";

export const PRIORITIES: Priority[] = [PriorityEnum.LOW, PriorityEnum.MEDIUM, PriorityEnum.HIGH];

export interface Board {
  id: string;
  name: string;
  ownerId: string;
  createdAt: string;
  updatedAt: string;
}

/** Board as listed on the dashboard, with aggregate counts (spec §10). */
export interface BoardSummary extends Board {
  columnCount: number;
  taskCount: number;
}

export interface Column {
  id: string;
  boardId: string;
  name: string;
  position: number;
  createdAt: string;
  updatedAt: string;
}

export interface Task {
  id: string;
  columnId: string;
  title: string;
  description: string;
  priority: Priority;
  position: number;
  dueDate: string | null;
  createdAt: string;
  updatedAt: string;
}

/** A column with its tasks attached, as returned by GET /api/boards/:boardId (spec §6). */
export interface ColumnWithTasks extends Column {
  tasks: Task[];
}

/** The full board detail payload, as returned by GET /api/boards/:boardId (spec §6). */
export interface BoardDetail extends Board {
  columns: ColumnWithTasks[];
}

/**
 * Mirrors the generated `Error` schema (src/api/generated/model/error.ts).
 * Not re-exported directly under that name because it would shadow the
 * built-in `Error` type wherever imported.
 */
export interface ApiErrorShape {
  error: {
    code: string;
    message: string;
  };
}
